spring.application.name=InteractiveNovelPlatform

spring.threads.virtual.enabled=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB


spring.datasource.url=jdbc:postgresql://localhost:5432/website
spring.datasource.username=postgres
spring.datasource.password=Hulk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration



app.guest.secret=p/zqDzVu1863FKBCnCWWMw6KLawTXbqvkkTVrxPbYPg=
jwt.secret=sXH1CSjd+zMFw/miSeOM52DMAKGhZr6Z8HlpulEqxFLV95vLTSfnKUrZftM5sdumsUccJH08VH12lrGcbfIo0A==
jwt.expiration=604800000


# Основной IP адрес сервера в локальной сети
app.server.ip=localhost

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://${app.server.ip}:5173

minio.endpoint=http://${app.server.ip}:9000
minio.accessKey=admin
minio.secretKey=Admin123453421
minio.bucketName=interactive-novel-assets
app.storage.base-url=http://${app.server.ip}:9000/${minio.bucketName}
app.storage.default-avatar=${app.storage.base-url}/avatars/default-avatar.png
app.storage.default-cover=${app.storage.base-url}/covers/default-cover.png


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=Hulk
spring.data.redis.timeout=2000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=223b90027326ff
spring.mail.password=69dbc9d832cc05

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



