spring.application.name=InteractiveNovelPlatform

spring.threads.virtual.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/website
spring.datasource.username=postgres
spring.datasource.password=Hulk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=sXH1CSjd+zMFw/miSeOM52DMAKGhZr6Z8HlpulEqxFLV95vLTSfnKUrZftM5sdumsUccJH08VH12lrGcbfIo0A==
jwt.expiration=604800000

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

minio.endpoint=http://127.0.0.1:9000
minio.accessKey=admin
minio.secretKey=Admin123453421
minio.bucketName=interactive-novel-assets

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=Hulk
spring.data.redis.timeout=2000