
ALTER TABLE novel ADD COLUMN IF NOT EXISTS total_score BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE novel ADD COLUMN IF NOT EXISTS rating_count INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE novel DROP COLUMN IF EXISTS average_rating;